'use client'

import dynamic from 'next/dynamic'
import { useState } from 'react'
import { AlertTriangle, ChevronDown, CircleHelp, CloudRain, Crosshair, Droplets, House, Layers3, MapPin, Menu, ShieldCheck, Siren, TriangleAlert, X } from 'lucide-react'
import { hazardZones } from '@/lib/hazard-overlays'

const RiskMap = dynamic(() => import('@/components/risk-map').then((module) => module.RiskMap), { ssr: false, loading: () => <div className="flex h-full min-h-[520px] items-center justify-center rounded-2xl border border-border bg-muted text-sm text-muted-foreground">Loading live map…</div> })

export function CitizenPortal() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedZone, setSelectedZone] = useState(hazardZones[2])
  return (
    <main className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border bg-card">
        <div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-8">
          <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck /></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-primary">NER RiskWatch</p><p className="text-xs text-muted-foreground">Citizen safety map</p></div></div>
          <nav className="hidden items-center gap-7 text-sm font-medium text-muted-foreground md:flex"><a className="text-foreground" href="#map">Risk map</a><a href="#prepare" className="transition hover:text-foreground">Prepare</a><a href="#help" className="transition hover:text-foreground">Help & resources</a></nav>
          <button className="rounded-lg p-2 text-muted-foreground md:hidden" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu /></button>
          <div className="hidden items-center gap-3 md:flex"><a href="/citizen-login" className="rounded-lg border border-border px-4 py-2 text-sm font-semibold transition hover:bg-muted">Citizen sign in</a><button className="rounded-lg border border-border px-4 py-2 text-sm font-semibold transition hover:bg-muted" onClick={() => alert('Incident reporting will be available next.')}>Report incident</button><button className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90"><CircleHelp />Emergency help</button></div>
        </div>
        {menuOpen && <div className="border-t border-border p-5 md:hidden"><button className="float-right" aria-label="Close menu" onClick={() => setMenuOpen(false)}><X /></button><div className="flex flex-col gap-4 pt-4 text-sm font-medium"><a href="#map" onClick={() => setMenuOpen(false)}>Risk map</a><a href="#prepare" onClick={() => setMenuOpen(false)}>Prepare</a><a href="#help" onClick={() => setMenuOpen(false)}>Help & resources</a></div></div>}
      </header>

      <section className="border-b border-border bg-muted/40"><div className="mx-auto flex max-w-[1500px] flex-col gap-5 px-5 py-7 lg:flex-row lg:items-end lg:justify-between lg:px-8"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-primary"><span className="size-2 rounded-full bg-primary" />Live public information</div><h1 className="max-w-3xl text-balance text-3xl font-semibold tracking-tight md:text-5xl">Know your risk. <span className="text-primary">Move with confidence.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground md:text-base">Check current flood and landslide conditions across Northeast India, find nearby safe places, and make informed decisions before severe weather arrives.</p></div><div className="flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3 text-sm"><div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary"><Crosshair /></div><div><p className="font-semibold">Location services</p><p className="text-xs text-muted-foreground">Use the map control to locate yourself</p></div></div></div></section>

      <section id="map" className="mx-auto grid max-w-[1500px] gap-5 px-5 py-6 lg:grid-cols-[minmax(0,1fr)_330px] lg:px-8"><div className="min-w-0"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Northeast India risk map</h2><p className="text-sm text-muted-foreground">Live basemap with current risk overlays</p></div><button className="hidden items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm font-medium md:flex"><Layers3 />Layers <ChevronDown /></button></div><div className="h-[62vh] min-h-[520px]"><RiskMap /></div><div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-destructive" />Critical</span><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-orange-500" />High</span><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-yellow-500" />Moderate</span><span className="flex items-center gap-2"><i className="size-3 rounded-full bg-primary" />Safe shelter</span><span className="ml-auto">Map data © OpenStreetMap contributors</span></div></div>

        <aside className="flex flex-col gap-4"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="mb-4 flex items-start justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-muted-foreground">Selected zone</p><h3 className="mt-1 text-xl font-semibold">{selectedZone.name.split(' - ')[0]}</h3></div><span className="rounded-full bg-destructive/10 px-2.5 py-1 text-xs font-bold capitalize text-destructive">{selectedZone.risk}</span></div><div className="flex items-center gap-3 border-y border-border py-4"><div className="flex size-10 items-center justify-center rounded-xl bg-destructive/10 text-destructive"><TriangleAlert /></div><div><p className="text-sm font-semibold capitalize">{selectedZone.type} watch</p><p className="text-xs text-muted-foreground">Conditions need attention</p></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{selectedZone.description}. Stay alert, avoid crossing flowing water, and check local advisories before travel.</p><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90" onClick={() => alert('Preparedness guidance coming next.')}>View safety guidance <ChevronDown /></button></div>
          <div className="rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex items-center gap-2"><CloudRain className="text-primary" /><h3 className="font-semibold">Current conditions</h3></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted/60 p-3"><Droplets className="mb-2 text-primary" /><p className="text-2xl font-semibold">78%</p><p className="text-xs text-muted-foreground">Rain chance</p></div><div className="rounded-xl bg-muted/60 p-3"><Siren className="mb-2 text-destructive" /><p className="text-2xl font-semibold">12</p><p className="text-xs text-muted-foreground">Active alerts</p></div></div><p className="mt-4 text-xs text-muted-foreground">Updated 8 minutes ago · Source: regional weather services</p></div>
          <div id="help" className="rounded-2xl bg-primary p-5 text-primary-foreground"><div className="flex items-start gap-3"><House /><div><h3 className="font-semibold">Find a safe place</h3><p className="mt-1 text-sm leading-5 text-primary-foreground/80">Turn on location to see nearby shelters, hospitals, and open routes.</p></div></div><button className="mt-4 flex items-center gap-2 text-sm font-semibold underline underline-offset-4" onClick={() => alert('Location access is available from the map control.')}>Use my location <MapPin /></button></div></aside>
      </section>
      <section id="prepare" className="border-t border-border bg-muted/30"><div className="mx-auto flex max-w-[1500px] items-center gap-3 px-5 py-5 text-sm text-muted-foreground lg:px-8"><AlertTriangle className="text-primary" /><p><strong className="text-foreground">If you are in immediate danger, call your local emergency services.</strong> This map supports awareness and does not replace official instructions.</p></div></section>
    </main>
  )
}
